# TRADING STRATEGY SETTINGS
TRADING_INTERVAL = 300  # 5 minutos em segundos
TRADE_PROBABILITY = 0.3  # 30% chance de trade
WIN_RATE = 0.65  # 65% win rate
MAX_TRADE_AMOUNT = 50  # Máximo $50 por trade
TRADE_PERCENTAGE = 0.05  # 5% do saldo por trade

# TRADING PAIRS (Moedas populares para bots)
TRADING_PAIRS = [
    "BTCUSDT", "ETHUSDT", "ADAUSDT", "DOTUSDT", "LINKUSDT",
    "MATICUSDT", "SOLUSDT", "AVAXUSDT", "ATOMUSDT", "ALGOUSDT"
]

# AI SETTINGS
AI_ANALYSIS_ENABLED = True
AI_LEARNING_RATE = 0.1
AI_MODEL_PATH = "ai_model.pkl"

# BYBIT SETTINGS
BYBIT_TESTNET = True  # Modo simulado padrão
BYBIT_API_KEY = "g9NOzMIa9Ye7lJ6QCI"
BYBIT_API_SECRET = "c9TdmpaeB0mxSmJQxa00BDevU6eT3Yze48X2"

# TELEGRAM SETTINGS
TELEGRAM_BOT_TOKEN = "8444269740:AAE2dlSXozV4cIGNMMs72APIDcrYBvIq31M"
TELEGRAM_CHAT_ID = "-4977542145"

# TELEGRAM NOTIFICATIONS
TELEGRAM_NOTIFICATIONS = True
NOTIFY_ALL_TRADES = True
NOTIFY_ENTRIES = True
NOTIFY_EXITS = True
NOTIFY_RESULTS = True
NOTIFY_AI_THOUGHTS = True

# WEB INTERFACE SETTINGS
HOST = "0.0.0.0"
PORT = 5000
FLASK_SECRET_KEY = "ultrabot_pro_secret_key_2024_v3"

# LOGGING AND MONITORING
LOG_LEVEL = "INFO"
SAVE_HISTORY = True
DEBUG_MODE = False

# RISK MANAGEMENT
MAX_DRAWDOWN = 0.1  # 10% máximo de drawdown
MAX_POSITION_SIZE = 0.1  # 10% do capital por trade
STOP_LOSS_PERCENTAGE = 0.02  # 2% stop loss
TAKE_PROFIT_PERCENTAGE = 0.04  # 4% take profit
