# TRADING STRATEGY SETTINGS
TRADING_INTERVAL = 300  # 5 minutos em segundos
TRADE_PROBABILITY = 0.3  # 30% chance de trade
WIN_RATE = 0.65  # 65% win rate
MAX_TRADE_AMOUNT = 50  # Máximo $50 por trade
TRADE_PERCENTAGE = 0.05  # 5% do saldo por trade

# TRADING PAIRS (Moedas populares para bots)
TRADING_PAIRS = [
    "BTCUSDT", "ETHUSDT", "ADAUSDT", "DOTUSDT", "LINKUSDT",
    "MATICUSDT", "SOLUSDT", "AVAXUSDT", "ATOMUSDT", "ALGOUSDT"
]

# AI SETTINGS
AI_ANALYSIS_ENABLED = True
AI_LEARNING_RATE = 0.1

# BYBIT SETTINGS - ✅ SEGURO: Use variáveis de ambiente
import os
BYBIT_TESTNET = os.getenv('BYBIT_TESTNET', 'True').lower() == 'true'
BYBIT_API_KEY = os.getenv('BYBIT_API_KEY', '')  # ✅ Vazio por padrão
BYBIT_API_SECRET = os.getenv('BYBIT_API_SECRET', '')  # ✅ Vazio por padrão

# TELEGRAM SETTINGS
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID', '')

# TELEGRAM NOTIFICATIONS
TELEGRAM_NOTIFICATIONS = True
NOTIFY_ALL_TRADES = True
NOTIFY_ENTRIES = True
NOTIFY_EXITS = True
NOTIFY_RESULTS = True
NOTIFY_AI_THOUGHTS = True

# WEB INTERFACE SETTINGS
HOST = "0.0.0.0"
PORT = 5000
FLASK_SECRET_KEY = "ultrabot_pro_secret_key_2024_v3"

# LOGGING AND MONITORING
LOG_LEVEL = "INFO"
SAVE_HISTORY = True
DEBUG_MODE = False

# RISK MANAGEMENT
MAX_DRAWDOWN = 0.1
MAX_POSITION_SIZE = 0.1
STOP_LOSS_PERCENTAGE = 0.02
TAKE_PROFIT_PERCENTAGE = 0.04
